var cartaNumbers = [
  "Carta No. 1",
  "Carta No. 2",
  "Carta No. 3",
  "Carta No. 4",
  "Carta No. 5",
  "Carta No. 6",
  "Carta No. 7",
  "Carta No. 8",
  "Carta No. 9",
  "Carta No. 10",
  "Carta No. 11",
  "Carta No. 12",
  "Carta No. 13",
  "Carta No. 14",
  "Carta No. 15",
  "Carta No. 16",
  "Carta No. 16",
  "Carta No. 18",
  "Carta No. 19",
  "Carta No. 20",
  "Carta No. 21"

  // Add more page titles as needed THIS IS CARTA NUMERO
];

var pageTitles = [
  "Causa y Efecto",
  "Recarga tu Luz",
  "Pedir por un Milagro",
  "Observa tus Pensamientos ",
  "Sanación",
  "Conéctate a Través de los Sueños",
  "Tu Estado Original",
  "Se Consciente de tu Energía Densa y/o Estrés",
  "Preguntemos a Nuestros Hermanos Mayores (Ángeles, Maestros, Guías…)",
  "Mal De Ojo",
  "Limpiar Nuestro Entorno",
  "Amor Incondicional",
  "Vivamos el Cielo en la Tierra",
  "Di NO a las Armas y la Violencia",
  "Visión Más Allá de lo Evidente",
  "Digo NO a la Depresión",
  "Salgo de Mi Encierro",
  "Creación",
  "Comunícate con tu Luz",
  "Supero Mis Adicciones",
  // 21
  "Abandonado"


  // this is Carta titulo
];

var pageContents = [
  "<span style='line-height: 1.5;'>En el mundo toda acción tiene una reacción. <br> Es decir, observa donde están dirigidos tus pensamientos (acción) y cuáles son las emociones que estas experimentado en este momento (reacción). <br>Por ejemplo, acción: si estas enfocado que no se puede ser feliz en la vida, por ende, te sentirás abrumado, amargado y hasta sin ganas de vivir. <br>Recuerda que hasta las palabras poco amables ponen en movimiento el principio de causa y efecto. <br>Ten en cuenta siempre que tu bienestar y el bienestar de los tuyos, es igual al bienestar común.  <br>Nuestra vida es y será el resultado de todas las decisiones, pequeñas y grandes que hemos tomado y tomaremos.",
  "<span style='line-height: 1.5;'>La incertidumbre y los cambios que enfrentamos es lo que hace que la vida sea excitante. <br> Algunos días tenemos toda la energía para enfrentar y disfrutar este viaje. Pero hay días en los cuales sentimos que nuestra Luz, la energía se ha disipado. <br>¿Por qué no podemos estar a nuestro tope todos los días?  Porque requerimos experimentar, en el tiempo de nuestra existencia, sentimientos y emociones buenas, malas, bonitas y feas que sin calificarlas son un aprendizaje de vida que te permiten ser más fuerte, más sabio y compasivo.  <br>Así mismo, date cuenta que cuando muestras egoísmo, intolerancia, miedo o rabia se crea una “energía densa” que contrarresta tu Luz.  <br>Esa falta de energía, es simplemente un mensaje de que necesitas ser consciente que eres una “Chispa de la Divinidad – una Energía del Universo - Creador” por ello conéctate nuevamente a tu Luz disfrutando de ese momento de quietud.  Reflexiona cual es el aprendizaje de la vivencia en ese momento, observando en tercera persona. Recuerda siempre: ¡Toda experiencia es una oportunidad de Aprendizaje! ",
  "<span style='line-height: 1.5;'>A veces nos encontramos en ciertas situaciones en las que sentimos que la única salida sería un milagro.  <br>Pero, debes partir que la Responsabilidad de tu vida es 100% tuya y de nadie más. <br>Que el evento que estás viviendo en este momento, TU lo creaste (YO lo cree), y cambia la pregunta de ¿Por qué? a ¿Para Qué - Cuál es el aprendizaje? <br>Si partes que el evento es creado por ti, así mismo, tú puedes crear la solución, realizar el milagro deseado, así como Jesús lo hizo, al igual que Moisés, Josué, y muchos más. <br>Ellos lo lograron a través de su Luz y la FE Incondicional invocando el nombre de Creador y en Confianza “Que se haga su Voluntad”.",
  "<span style='line-height: 1.5;'>¿De dónde provienen los pensamientos negativos que se vuelven hasta obsesivos compulsivos? <br>Muchas veces, provienen de emociones atrapadas y atascadas dentro de ti, y especialmente del ego que te hace sentir como la víctima o el pobrecito Yo. El ego manipula tus sentimientos y emociones constantemente, generando pensamientos recurrentes que te llevan a un estado de ansiedad, preocupación, miedo, envidia, celos, ganas de vengarte o amargura. <br>Es importante que aprendas a reconocer y liberar estas emociones atrapadas para poder superar los pensamientos negativos y obsesivos. <br>Si, por el contrario, al realizar un trabajo o labor, ya sea que te guste o no, te enfocas en agradecer y sentir en cada respiración la fuerza de tu Luz Espiritual de manera consciente, tus pensamientos se acallan y en ese momento sientes tranquilidad y serenidad. <br>Tu mente se libera y tu corazón se abre y se siente cálido, lo que te permite soltar tus conductas obsesivas. Agradecer y conectarte con tu Luz Espiritual puede ayudarte a encontrar la paz interior y la serenidad que necesitas para enfrentar cualquier situación. A través de la práctica constante, puedes aprender a liberarte de los pensamientos negativos y obsesivos y a encontrar la felicidad y la realización personal que mereces. ",
  "<span style='line-height: 1.5;'>Culpar a alguien más por nuestras dolencias, enfermedades o sufrimientos puede ser una forma fácil de evadir la responsabilidad. <br>Sin embargo, si realmente quieres sanarte en todos los sentidos (material, físico, mental, emocional y espiritual), debes asumir la responsabilidad de que la dolencia, enfermedad o sufrimiento te lo has causado tú mismo. <br>Es muy importante que comprendas que lo que estás viviendo en este momento es una oportunidad para tu DESPERTAR y desarrollo personal.  <br>Asumir la responsabilidad de tu propia vida puede ser difícil, pero es fundamental para tu crecimiento y sanación. <br>A través de la reflexión, la meditación, la práctica constante, y entiendes el aprendizaje (comprendes el motivo, la causa de porque vives o viviste dicho evento), encontraras la fórmula para sanarte y a encontrar la felicidad y la realización personal que mereces. Estas despertando tu Luz para Sanarte. ¡No te rindas, sigue adelante en tu camino hacia la sanación y el despertar! ", "La vida transcurre en varias dimensiones, y una de ellas es la de los sueños. En nuestros sueños, podemos recibir respuestas a nuestras dudas e interrogantes, y podemos pedir que se nos revele la solución, el camino o la guía a seguir. Los sueños pueden ser una herramienta poderosa para nuestra transformación y crecimiento personal. A través de la práctica constante, podemos aprender a conectarnos con nuestro subconsciente y a recibir mensajes importantes que nos ayuden a tomar decisiones y a encontrar la felicidad y la realización personal que merecemos.  <br>No subestimes el poder de tus sueños. <br>Pide que se te revele la solución a tus problemas y confía en que recibirás la guía que necesitas para avanzar en tu camino. ¡Sigue adelante en tu búsqueda de la verdad y la sabiduría! ",
  "<span style='line-height: 1.5;'>Nuestro estado original es de Orden y Perfección el otro extremo reina el caos, donde tu vida la sientes fragmentada y desarticulada, no tienes tranquilidad o calma, te sientes confundido.  <br>Si recuerdas que viniste a aprender y desarrollar el Orden y la Perfección Universal, ligados directamente a las Fuerzas de la Creación, puedes ver el caos de una manera diferente. <br>En lugar de sentirte abrumado por las pruebas y desafíos de la vida, puedes verlos como oportunidades para aprender y crecer. <br>Cada situación difícil que enfrentas es una oportunidad para desarrollar tu fortaleza y tu sabiduría. <br>A través de la reflexión y la práctica constante, puedes aprender a encontrar el orden y la perfección en medio del caos y a encontrar la felicidad y la realización personal que mereces. <br>No te rindas ante las pruebas de la vida. <br>Recuerda que estás aquí para aprender y desarrollar tu potencial, y que cada desafío es una oportunidad para crecer. ¡Sigue adelante en tu camino hacia el Orden y la Perfección Universal! ",
  "<span style='line-height: 1.5;'>Cuando te sientes ansioso, molesto por todo, sin rumbo o sin ganas de hacer nada, o, por el contrario, te encuentras acelerado, corriendo de un lado para el otro, o en un estado de tristeza, depresión, hostilidad, incertidumbre o miedo, es importante que te detengas y te digas: ¡BASTA Ya! Ya estoy cansado, no puedo más. Quiero cambiar.  Quiero vivir la vida y lograr mis metas. <br>Tomar la responsabilidad de tu vida es fundamental para tu crecimiento y bienestar. Si quieres cambiar y lograr tus metas, el primer paso es tener la convicción de que puedes hacerlo.<br> Debes salir de la victimización y aprender de las enseñanzas de la vida. ",
  "<span style='line-height: 1.5;'>Se consciente que siempre estas acompañado y apoyado por Nuestros Hermanos Mayores (Ángeles, Maestros, Guías…), que son una partícula de energía del Creador, como Tú también lo eres. <br>A ellos hay que agradecerles porque nos guían para encontrar nuestro camino, sin importar cuantas veces nos desviamos de él, nos vuelven a mostrar la ruta para retornar a ella. <br>Así mismo, nos apoyan en nuestra existencia, para que nos demos cuenta de nuestras propias capacidades y salgamos de las lamentaciones que nos detienen en aprender lo que nos enseña cada evento (bueno, bonito, malo, feo) que atravesamos en la vida. <br>Entendiendo ¡Qué tengo que aprender!, y cuando aplico la Enseñanza te sientes más tú (sientes más a tú propio SER). Solo nos recuerdan también que cuando nos comportamos con Tolerancia, Compasión – Amor y Paz con nosotros y con las demás personas están más cerca nuestro y se nos facilita escucharlos en sus orientaciones, pero, es nuestra decisión aplicarla (ellos no pueden hacer nuestra tarea).  ",
  "<span style='line-height: 1.5;'>Es una tradición en muchas culturas del mundo. <br>La nombran como un arma y como culpable de muchas guerras y de las desgracias de cada día. <br>El “Mal de Ojo” puede ser una mirada resentida o una ojeada negativa que recibimos de una persona con sentimientos nocivos contra nosotros.  <br>Se dice que todos lo poseemos ya que el ojo humano tiene la capacidad de transmitir tanto energía negativa como positiva.  <br>De otra parte, cuando lanzamos “Mal de ojo” contra otras personas creamos una apertura “negativa” de energía densa en nosotros mismos, atrayendo los efectos dañinos que la acompañan. <br>Por lo tanto, el mal de ojo causa daño igual a quien lo lanza como al que lo recibe. ¿Por qué nos pueden afectar Porque no tenemos la Fuerza de Voluntad para repeler esas “malas intenciones”?. ",
  "<span style='line-height: 1.5;'>Situaciones negativas como confrontaciones, enojos, depresiones, tristezas, entre otras dejan, en el entorno donde se produjo el evento, “residuos energéticos negativos” que se adhieren a los diferentes elementos (paredes, cuadros, techo, piso, entre otros) por lo que se requiere hacer una limpieza energética al ambiente. <br>Cuando las cosas en el trabajo o en la casa son caóticas, frecuentemente el “culpable escondido” son los residuos producidos por los eventos negativos acaecidos allí. <br>Así mismo, cuando nos mudamos a un hogar nuevo o establecemos un nuevo negocio debemos limpiarlos de memorias impregnadas (partículas negativas o residuos no deseados). ",
  "<span style='line-height: 1.5;'>El amor es una fuerza muy poderosa, es una herramienta de Luz que puede erradicar toda forma de negatividad y oscuridad. <br>La frase “ama a tu prójimo como a ti mismo”, tiene mucha profundidad en la que debemos meditar. Para dar algo primero debemos poseerlo. <br>Para dar Amor debemos primero amarnos a nosotros mismos. <br>A veces se nos hace difícil el amarnos. <br>Pero cuando lo logramos, es muy fácil Amar a nuestro prójimo, inclusive a quienes consideramos nuestros enemigos.  <br>Emulemos y esparzamos el Amor del Creador por toda la Humanidad creando Armonía entre nuestro Ser, a los demás y al mundo natural. <br>Demos Amor a nuestra familia, amigos y a todos con quien nos cruzamos. ",
  "<span style='line-height: 1.5;'>¿Cómo imaginas tu vida en el cielo? <br>Podrías considerarlo como un lugar de plena armonía, paz y felicidad tanto a nivel personal como a nivel global. Deberías preguntarte: <br>¿Por qué no disfruto el cielo en la tierra? <br>Parte del hecho de que el destino de disfrutar el cielo o el infierno en la tierra está basado y cimentado en tu propia disposición ante la vida, pues tu eres quien crea tu propia existencia. <br>Para lograr esto, primero debes lograr tu propia liberación y recuperación interna a través de la transformación personal. <br>Como dice el refrán, 'si quiero cambiar el mundo, empiezo por mí'. <br>Solo así podrás crear un mundo mejor y disfrutar del cielo en la tierra. <br>Para la liberación global reúnete con personas que quieran también alcanzar el cielo en la tierra, hasta lograr conseguir la masa crítica. ",
  "<span style='line-height: 1.5;'>Debemos partir que nuestras acciones contras otros tienen un impacto en el resto de la humanidad, lo que se conoce como el “Efecto Mariposa”. <br>Es decir, Si nos portamos violentos contra otra persona, estamos afectando el estado de consciencia del planeta. <br>Ya que este estado es la suma de la consciencia individual de todas las personas. Démonos cuenta que la intolerancia y la hostilidad son el comienzo de los actos violentos y el conflicto entre los individuos es el comienzo de las guerras entre pueblos y naciones. <br>Cuando un pueblo está en conflicto interno o contra otra nación, es un pueblo que se encuentra en oscuridad Espiritual. Incluso si se usa violencia para combatir la violencia, la oscuridad Espiritual se encuentra en ambos lados, se está usando oscuridad contra oscuridad. Por ello, la única forma de lograr y alcanzar la verdadera paz es encontrarla en tu luz Espiritual, en tu Corazón y en tu Alma. ",
  "<span style='line-height: 1.5;'>La visión más allá de lo evidente es aquella que nos permite ver más allá de lo que está a simple vista. <br>Es una habilidad que nos permite explorar nuevas posibilidades, descubrir soluciones creativas y encontrar oportunidades donde otros solo ven obstáculos.  <br>Esta visión nos permite ir más allá de nuestras limitaciones y alcanzar nuestros objetivos más ambiciosos. Para desarrollar esta habilidad, es necesario cultivar la curiosidad, la imaginación y la capacidad de pensar fuera de la caja. <br>Solo así podremos ver más allá de lo evidente y alcanzar nuestro máximo potencial. ",
  "<span style='line-height: 1.5;'>Cada día nos encontramos con obstáculos, problemas y situaciones que resolver. Si nos sentimos abrumados por ellos podemos creer que no somos suficientes y llegar a la depresión. <br>O si cualquier día nos levantamos con el ánimo abatido y no queremos nada, puede ser que estemos deprimidos. <br>La depresión se puede convertir en un estado emocional muy atractivo, porque simplemente no hacemos nada, nos sentamos o acostamos pasivamente, la gente que nos conoce puede sentir lástima. Pero al mantenernos, en este estado, se va empeorando a cada momento, ya que se retroalimenta y cada vez es más difícil salir. <br>Por eso es importante crear un sistema de alarma cuando estemos deprimidos o nos sintamos con duda y desesperanza. <br>Debemos aprender a levantarnos y seguir adelante, lo importante no es caer, la verdadera grandeza es levantarse de nuevo. ",
  "<span style='line-height: 1.5;'>Es tal el miedo que tenemos que nos encerramos en una burbuja, porque sentimos la necesidad de protegernos, porque creemos que todo el mundo nos ataca o nos va a hacer daño, y esa burbuja nos ayuda de cierta manera a tener una relativa seguridad, pero la verdad nos evita vivir la vida. <br>Nuestro ego nos protege, pero también es la base de todas las formas de miseria. <br>Estamos en presión constante de superar nuestros compañeros de trabajo, de nuestros vecinos y hasta de nuestros amigos; tratamos de agradarle a todo el mundo. <br>Nos sometemos a una carrera sin sentido de tener lo más nuevo, moderno y de moda, aunque no lo necesitemos. <br>Está presión social en la que estamos sumergidos, es alimentada permanentemente por nuestro ego. Nos mantiene en una lucha por demostrar que siempre estamos en lo correcto, incluso aun cuando sabemos que estamos equivocados. El ego nos mantiene prisioneros de sus deseos dándonos la ilusión que actuamos con libertad. ",
  "<span style='line-height: 1.5;'>Cuando eres responsable de ti y tomas tus propias decisiones, creas, diseñas y vives la vida que decidiste construir. <br>Así mismo, cuando das Luz a nuevas ideas o negocios, estas hablando de tu capacidad de crear. Al tener una idea nueva, aún necesitas desarrollarla, planificarla, volverla tangible y materializarla. <br>Lo mismo ocurre cuando empiezas un negocio: debes darle nacimiento, nutrirlo y cuidarlo para que crezca y prospere. Como seres humanos, hijos del Creador, tenemos el poder de la creación. <br>Es nuestro derecho y nuestra responsabilidad utilizar este poder para crear una vida fértil y abundante para nosotros y para los demás. <br>Para hacer realidad nuestras ideas y proyectos, debemos tener una visión clara y un plan de acción concreto. <br>Debemos ser perseverantes y estar dispuestos a trabajar duro para alcanzar nuestras metas. Al mismo tiempo, debemos ser flexibles y estar abiertos a ajustar nuestro plan si es necesario. La creatividad y la innovación son clave para el éxito en cualquier empresa, y debemos estar dispuestos a explorar nuevas ideas y enfoques para lograr nuestros objetivos. Al utilizar nuestro poder de la creación de manera consciente y sabia, podemos crear una vida llena de significado y propósito. Podemos contribuir al bienestar de los demás y del mundo que nos rodea, y dejar un legado positivo para las generaciones futuras. La creatividad y la innovación son herramientas poderosas que nos permiten hacer realidad nuestros sueños y alcanzar nuestro potencial máximo como seres humanos. ",
  "<span style='line-height: 1.5;'>La Luz, nuestra Luz es la energía de Creador que es imperecedera, nunca se apaga, nunca se nos niega porque somos sus hijos e hijas. <br>Es la Fuente Infinita de Poder a la que siempre estamos conectados y tenemos acceso ilimitado.  <br>Pero este acceso ilimitado es bloqueado cuando somos dominados por nuestro ego, por nuestra actitud negativa, por nuestras palabras poco amables o destructivas.  <br>Por ello es nuestra labor el mantener limpio este canal de conexión al ser responsables de nuestros actos con nosotros mismos y con los demás. ",
  "<span style='line-height: 1.5;'>En nuestra transformación, nos enfrentamos a diversos retos que debemos superar. <br>Sin embargo, quizás el mayor de ellos sea el de las adicciones y las influencias de nuestro ego. <br>Nuestro ego nos impulsa a querer todo de manera inmediata y sin esfuerzo alguno.  Deseamos ser felices ahora mismo, que todos nos amen de inmediato y, en cuanto a las cosas materiales, pretendemos tener todo lo que podamos imaginar sin tener que hacer mucho por lograrlo. <br>La gratificación inmediata es algo muy tentador, pero debemos aprender a controlarla para poder avanzar en nuestra transformación. <br>Además, es mucho más fácil someterse a los caprichos del ego que trabajar con disciplina, constancia y felicidad por lo que queremos. ",
  // 21
  "<span style='line-height: 1.5;'>Hay días que nos sentimos que nadie nos entiende, nadie nos quiere, es un sentimiento de abandono y soledad que nos arruga el corazón y no queremos hacer nada solamente gritar, llorar nuestro infortunio.   <br>Pero si le pones atención a tu corazón te das cuenta que él se siente abandonado por ti. <br>Habla con tu corazón cuéntale como te sientes lo abrumado que estás y la desesperanza en la que te encuentras. <br>Pídele perdón a tu corazón por tenerlo olvidado y no escucharlo. Vuélvelo a sentir, que al ser consciente de él se alegrará y le dará Luz a tu vida.   "
  // This is carta Descripcion
];

// var contentSnippets = [
//   "En el mundo toda acción tiene una reacción. Es decir, observa donde están dirigidos tus pensamientos (acción) y cuáles son las emociones que estas experimentado en este momento (reacción). Por ejemplo, acción: si estas enfocado que no se puede ser feliz en la vida, por ende, te sentirás abrumado, amargado y hasta sin ganas de vivir.",
//   "Content 2",
//   "Content 3"

// ];

var contentMeds = [
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención a 5cm encima del ombligo (R17 del meridiano del riñón: armoniza el estómago y estimula la digestión).  <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten tomar tus decisiones (repite tres veces o hasta que sientas que no esté tenso).  <br>Ahora, imagínate que sacas de una célula de tu cuerpo el cromosoma No. 3 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de memorias limitantes, implantes generacionales que te obstaculizan. <br>•	Así mismo, se organiza, armoniza y activa su parte dormida el cromosoma 3.",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día. <br>Mira las figuras y enfoca tu atención:   •	En el centro del entrecejo   •	Al mismo tiempo a 2 - 3 cm a la izquierda del centro del pecho (R22 meridiano del riñón: alivia el dolor torácico).    <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión en estos puntos, con la intención de soltar los sentimientos atrapados que no te permiten la conexión con la fuente para recargar tu Luz (repite tres veces o hasta que sientas que no esté tenso).         <br>Ahora, imagínate que sacas de una célula de tu cuerpo el cromosoma No. 4 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar – purificar:  <br>•	Los códigos que te dan perplejidad, falta de sostén, te anulan tu Ser, te desorientan, te obstruyen, te esclavizan.  <br>•	Así mismo, se organiza, se armoniza, y activa la parte dormida del cromosoma 4.",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.    <br>Mira la figura y enfoca tu atención en la parte posterior del ombligo (Du4 meridiano Gobernador: tonifica el riñón y nutre la energía) y en el genital derecho (BP 12. meridiano del bazo-páncreas: ordena la energía).  <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión e imagínate que le quitas un tapón (repite tres veces), con la intención de soltar los sentimientos atrapados que no te permiten ser responsable de ti misma/o y lograr que ocurra el milagro en tu vida.  <br>Ahora, Imagínate que sacas de una célula de tu cuerpo el cromosoma No. 6 introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso con la intensión de Limpiar y purificar:  <br>•	Los códigos de la Culpa, de guardar – atesorar, de la avaricia.   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 6.  <br>Pon atención a tu corazón y desde ahí manifiesta en voz alta:   “Le pido al Creador, a mi Maestro – Guía, a mi Ángel Guardián me apoyen, me guíen y me concedan liberarme de estos sentimientos, a través de la purificación de mi cuerpo, mente, emociones y Espíritu” <br>(Repítelo tres veces).   ",  
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en el perineo (entre el ano y tú parte sexual JM1: despeja la fuerza espiritual y despierta los sentidos).   <br>Imagínate que le quitas una tapa al perineo y deja salir todo lo acumulado, se puede sentir, a veces, como si te estuvieras destapando una cañería, no lo detengas deja que salga todo lo que está ahí guardado y esa energía estancada que no te permiten salir de esos pensamientos recurrentes.      <br> Ahora, imagínate que sacas de una célula de tu cuerpo el cromosoma No. 16 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de las sombras que ocultan a tu Yo Superior   •	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 16.   ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la base del cráneo. Siente esa parte del cuerpo imagínate que retiras una lámina y/o acumulaciones (pegotes) de la base del cráneo para soltar los sentimientos atrapados que no te permiten realizar tu sanación.      <br>Ahora, Imagínate que sacas de una célula de tu cuerpo los cromosomas No. 20 y 21 y lo introduces en una vasija de jade lleno de Jade líquido de un verde intenso con la intensión de limpiar y purificar:  •	Los códigos de la dualidad, el no querer saber la verdad, no querer avanzar, sentir que todo es injusto.  <br>•	Así mismo, se organizan, armonizan y activa su parte dormida los cromosomas 20 - 21.    <br>Sigue estos pasos:  <br>1.	Primero, reflexiona que es lo que te quiere enseñar.   <br>2.	Segundo, a través de la aplicación de su aprendizaje irás sanando tu dolencia.   <br>3.	Tercero, recuerda que la responsabilidad de tus decisiones es completamente tuya. <br>Todo lo ocurrido, que te ocurre y ocurrirá en tu vida es tu responsabilidad y de nadie más.   ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b>(ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día  <br>Mira la figura y enfoca tu atención en la palma de la mano derecha. Siente esa parte del cuerpo imagínate que te quitas un guante con la intención de soltar los sentimientos atrapados que no te permiten manifestar los sueños de tu Corazón. <br>Ahora, <br>Imagínate que sacas de una célula de tu cuerpo el cromosoma No. 22 y lo introduces en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar: •	Los códigos del EGO que no te permiten encontrarte con tu YO SUPERIOR •	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 22. ",  
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br>Deja que afloren los sentimientos <b>¡NO! los califiques</b>s (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira las figuras y enfoca tu atención al lado izquierdo de la cintura en la parte inferior del costillar (E 24 del meridiano del estómago: libera la Energía Espiritual, armoniza el estómago)      <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto e imagínate que quitas un tapón (Repite tres veces), con la intención de dejar salir toda la energía estancada del cuerpo y a soltar los sentimientos atrapados que no te permiten mantenerte en tu estado original.  <br>Ahora, imagínate que sacas de una célula de tu cuerpo el cromosoma No. 15 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso con la intensión de limpiar, purificar y armonizar:  <br>•	tu Niño – Niña Interior.   <br>•	Así mismo, se organiza, armoniza y activa su parte dormida del cromosoma 15.  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos.<br> Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la parte superior de la espalda, alineado a la derecha del disco T2-T3 sobre el omóplato (V 42 meridiano de la vejiga: Entrada al alma).  <br>Inhala y al exhalar imagínate que quitas un tapón (Repite tres veces), con la intención de dejar salir toda la energía estancada del cuerpo y a soltar los sentimientos atrapados que no te permiten estar en Paz contigo y con los demás.  Ahora, imagínate que sacas de una célula de tu cuerpo el cromosoma No. 13 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	tu campo magnético, los códigos de la desarmonía, ataduras, inseguridad, miseria, tormentos.   <br>•	Así mismo, se organiza, armoniza y activar su parte dormida del cromosoma 13.  ",  
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en:   •	A la altura del 3er ojo  •	en la encía directamente encima del diente medio, justo bajo la base de la nariz (TM 26 meridiano gobernador: aclara el cerebro despierta los sentidos)   <br>Imagina que estás quitando un tapón en ese punto, con la intención de liberar toda la energía estancada en tu cuerpo. <br>Este ejercicio te ayudará a soltar todo aquello que te impide la comunicación filial, sentir la presencia de Nuestros Hermanos Mayores y reconocer el apoyo que te brindan.     <br>Ahora, imagínate que sacas de una célula de tu cuerpo el cromosoma No. 12. Introdúcelo en una vasija de jade con Jade líquido de un verde intenso con la intensión de limpiar y purificar:  <br>•	los códigos de desconexión con nuestros Hermanos Mayores   <br>•	Así mismo, se organiza, armoniza y activa su parte dormida del cromosoma 12.  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en: la 3ª vértebra torácica; sobre la línea media de la espalda (TM 12: libera la energía espiritual, fortalece el cuerpo).  <br>Imagínate que retiras, una especie de corcho o tapón, en ese punto del meridiano, con la intención de soltar los sentimientos atrapados que no te permiten sentir tu fuerza de voluntad.     <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 13 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  •	las influencias proyectadas por otros hacia ti recuperando tu fuerza de voluntad personal.   <br>•	así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 13.  <br>Comienza a retirarte una envoltura pesada alrededor de tu cuerpo, como símbolo que eliminas ese “mal de ojo”. Observa como respiras mejor y el cuerpo se siente más liviano, menos atascado. Y tienes una mayor claridad.  <br>Con la intención desde tu corazón alinea el chakra raíz (ubicado en toda la punta de la columna vertebral) y despójalo de todas las impurezas (miedos, inseguridades, depresión…)  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día. <br> Mira la figura y enfoca tu atención parte posterior del centro del corazón en la espina dorsal (TM 10 del meridiano gobernador: monumento del alma: apoya procesos de cambios).   <br>Imagínate que retiras, una especie de corcho o tapón, en ese punto del meridiano, con la intención de limpiar – purificar esos sentimientos atrapados en ti que se pueden esparcir en tu ambiente.     <br>Así mismo, enfócate en el centro de la vivienda donde estas (casa, apartamento, oficina, finca…) pon la intención de limpiar, purificar y armonizar el lugar visualizando un torbellino que empieza a emerger retirando todo aquello que no te permite seguir avanzando en tu proceso de vida.  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la parte central de la espalda (TM 9 del meridiano gobernador: ordena la energía, sostiene el corazón infantil la humanidad).   <br>Imagínate que retiras, una especie de corcho o tapón, en ese punto del meridiano, con la intención de soltar los sentimientos atrapados que no te permiten expresar el Amor Incondicional.     <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 9 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	los códigos de la manipulación y el control   <br>•	así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 9.  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención a 5cm debajo del ombligo (JM5. Meridiano Vaso concepción: ordena la energía; activa nuestra conexión con el yo superior y la experiencia de la paz en nuestras vidas)   <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten vivir el cielo en la Tierra.     <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 13 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	los códigos de la desarmonía, los tormentos humanos, los apegos   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 13.   ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la parte central posterior del cuello entre las Cervicales 1 y 2 (TM 15, meridiano gobernador: aclara el cerebro y despierta los sentidos).   <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten vivir tu Paz interna.     <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 11 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos del odio que se alojan en ti todavía y entre los hermanos humanos (todos somos hijos e hijas de Creador).   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 11.  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención a aproximadamente 2 cm a la izquierda del ojo izquierdo (VB 3 Meridiano de la Vesícula Biliar: Huésped y anfitrión; fluye la conexión con el yo superior)   Siente esa parte del cuerpo para que apoyes a soltar los sentimientos atrapados que no te permiten ver más allá delo evidente.      <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 16 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de las sombras que ocultan a tu Yo superior.   <br>•	así mimo, se organiza, armoniza y activa la parte dormida del cromosoma 16.  ",
  "<span style='line-height: 1.5;'>scucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención detrás de la rodilla derecha (V 40 Meridiano de la vejiga: equilibrio perfecto)   Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten vivir tu conexión con tu Yo superior y con su guía tomar tus decisiones.     <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 15 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	las sombras que ocultan a tu Niño Interior.   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 15.   ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en el tobillo izquierdo (V 62 Meridiano de la vejiga: desarrollar la paciencia, el equilibrio y activa la verdad de nuestra inteligencia de Creador).  <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten salir de tu encierro.     Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 16 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de las sombras que ocultan a tu Yo superior, la sumisión de entregar tu poder a otros.   •	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 16.   ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la palma de la mano derecha (MC 8 Meridiano del pericardio: libera la fuerza espiritual; conexión de la humanidad con su capacidad para manifestar los sueños de su corazón.  <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten manifestar la creación.     <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 5 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de las sombras que ocultan la Libertad de SER.   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 5.   ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la parte posterior interna de la pierna derecha a medio camino entre el tobillo y la rodilla (H 6 Meridiano del hígado: nutre y calma la sangre, moviliza la energía)   <br>Inhala y al exhalar con el dedo índice o del medio, aplica una presión a ese punto, con la intención de soltar los sentimientos atrapados que no te permiten mantener tu conexión con tu Luz.    <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 13 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de la desarmonía.   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 13.  ",
  "<span style='line-height: 1.5;'>Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos <b>¡NO! los califiques</b> (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.  <br>Mira la figura y enfoca tu atención en la parte posterior del cuerpo a aproximadamente 3 cm a la derecha (V 50 Meridiano de la vejiga: armoniza el estómago.  <br>Imagínate que retiras, una especie de corcho o tapón, en ese punto del meridiano, con la intención de soltar los sentimientos atrapados que no te permiten superar tus adicciones.  <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 8 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar:  <br>•	Los códigos de las sombras que ocultan la VERDAD.   <br>•	Así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 8.   ",
  // 21
  "<span style='line-height: 1.5;'Escucha la melodía y permítete fundirte en ella por tres minutos. <br>Deja que afloren los sentimientos ¡NO! los califiques (ni de buenos ni de malos), solo acéptalos y exprésalos. <br>Sigue escuchando la melodía mientras realizas la meditación y si es posible escúchala todo el día.   <br>Mira la figura y enfoca tu atención en la parte posterior del cuerpo (TM 5 Meridiano Gobernador o del vaso: refuerza la energía Yang). <br>Imagínate que retiras, una especie de corcho o tapón, en ese punto del meridiano, con la intención de soltar los sentimientos atrapados que no te permiten liberarte de sentirte abandonado/a.   <br>Adicionalmente imagínate que sacas de una célula de tu cuerpo el cromosoma No. 14 e introdúcelo en una vasija de jade lleno de Jade líquido de un verde intenso, con la intensión de limpiar y purificar: <br>•	Los códigos de las sombras que no te permiten desplegar tu propio SER, tu propia LUZ. <br>•	así mismo, se organiza, armoniza y activa la parte dormida del cromosoma 14. "

  // This is carta Meditacion
];

var contentAfirs = [
  "<span style='line-height: 1.5;'>Pon atención a tu corazón y desde ahí Di en voz alta:  <br> “Reconozco y Acepto que tengo miedo de tomar mis propias decisiones, de fallar, miedo al fracaso y la impotencia que ello me acarrea (Repítelo tres veces)” <br> Inhala y al exhalar por la boca (hasta dejar los pulmones vacíos) siente como se sueltan los bloqueos que te impiden tomar tus propias decisiones y las emociones que emergen, sin trancarlas déjalas que se manifiesten.  <br> Si todavía sientes traba en alguna parte del cuerpo vuelve a repetir por tres veces más hasta que sientas descanso en el cuerpo.  <br> Pon atención a tu corazón y desde ahí manifiesta:  <br> “Me conecto con mi Luz que se encuentra dentro de mi corazón.  <br> Agradezco por las experiencias vividas que me permiten crecer. <br>  Siento la fuerza de mi interior para asumir por completo   la Responsabilidad de mi vida. <br> Soy consciente que todas mis decisiones tendrán un resultado” (Repítelo tres veces)  <br>  Durante el día expresa esta frase hasta completarla 72 veces (siempre sintiendo el corazón): <br> “Confío en que mi decisión es la mejor para esta etapa en mi vida”  ",
  "<span style='line-height: 1.5;'>Pon atención a tu corazón y desde ahí manifiesta en voz alta:  <br> “Reconozco y Acepto que mis heridas mentales me llevan al egoísmo, a la intolerancia, a la rabia, al miedo (Repítelo tres veces)”  Siente como se sueltan los bloqueos que te impiden sentir tu Luz que salen por estas partes del cuerpo. <br>Agradece por las experiencias vividas (buenas - malas, bonitas, feas) hasta este momento de tu existencia, entendiendo que tú misma/o la creaste para experimentar la dualidad y en este estado de velo comprender que siempre estás conectada/o con tu Luz.  <br>Ahora di:  “Millones de chispas sagradas que vienen del Mundo Superior y la Energía de la Madre GAIA retornan a mí, a mi Alma, a mi Espíritu.  <br>Mi vida crece con más brillo y Energía todos y cada uno de los días” (Repítelo tres veces)  Durante siete (7) días seguidos, tomate un tiempo para reflexionar o meditar acerca de ti misma/o con la intención de:  “Me conecto con mi Luz, me reconozco en mi Esplendor y recupero mi Entusiasmo, ahora soy más Energética/o, Sabia/o y Alegre”  ", 
  "<span style='line-height: 1.5;'>Ahora di:   <br>“Te entrego desde mi Corazón este deseo para que a través de tu Luz se materialice en mi vida. <br>Quedo en actitud de espera incondicional. Tengo la certeza que voy a recibir lo que necesito en el momento apropiado en mi vida” (Repítelo tres veces).  <br>Durante 21 días repite 72 veces al día,   <br>“Yo Soy (di tu nombre) Responsable de mi vida y me hago cargo de mi Existencia. <br>Yo Soy quien hace los milagros a través del Amor de Creador (Universo)”  ",
  "<span style='line-height: 1.5;'>Fíjate que cuando estas en un estado emocional obsesivo tu ego es quien te controla. <br>Por ello, habla con él y desde tu corazón le dices:  <br>Siente a tu corazón (¿Cómo está latiendo?) y desde ahí manifiesta en voz alta:  <br>“Reconozco que estás tratando de protegerme y te lo agradezco. <br>Eres parte de mi vida y sé que cuidas de mí.   <br>Ahora te pido que me APOYES para que mi mente y corazón reciban y se mantengan en la Luz del Creador” (Repítelo tres veces).  <br>Realiza este ejercicio durante tres días seguidos repitiéndolo tres veces en el día.  ",  
  "<span style='line-height: 1.5;'>Ahora, pon atención a tu corazón y desde ahí manifiesta en voz alta: <br> “Acepto mi responsabilidad sin juzgarla ni criticarla, y me comprometo a trabajar en mi desarrollo personal y en mi sanación. ¡Sigo adelante en mi camino hacia la transformación y la felicidad!” (Repítelo tres veces).  <br>Siente como se van removiendo las emociones…   <br>Ahora di:   “Desde mi corazón me perdono y siento como esta energía aligera todas mis dolencias. <br>Doy las gracias y reconozco que aprendí (expresa lo que aprendiste). <br>Asumo la Responsabilidad de mi vida física, emocional, mental, económica y espiritual” (Repítelo tres veces).  <br>Durante siete (7) días repite tres veces:  “Me conecto desde la Luz de mi corazón con aquellos que también necesitan curación, ayudando a transmitir las fuerzas de la curación, y dejo la mentalidad de víctima. Entre más comparto la Luz de la sanación más la recibo”.  ",  
  "<span style='line-height: 1.5;'>Esta noche cuando estés listo para dormir, realiza una meditación de conexión con el Creador (Universo) <br>y solicita que en el sueño te sea revelado y puedas encontrar la respuesta a tu inquietud, o con la intención de conversar con Tu Maestro - Guía o simplemente pide tener un sueño tranquilo y despertarte en buen estado de ánimo.   <br>Nota: Pide recordar tu sueño. Puedes llevar un diario detallado de tus sueños, en el cual antes de levantarte anota lo que recuerdas de ellos.   ",
  "<span style='line-height: 1.5;'>Pon atención a tu corazón y desde ahí manifiesta: <br>  “Reclamo mi Energía que entregue a otras personas (mis padres, hermanos, pareja, compañeros, hijos, jefes…) pido a mis Hermanos Mayores que la Purifiquen y la integro nuevamente en mi Campo Energético. <br>Reestablezco mi Energía y mi LUZ en mi Corazón.  <br> Siento esta energía que me llena y ocupa todos los espacios vacíos dentro de mí. <br>Siento la Plenitud y a mi niño interior que me permite disfrutar la Vida (Repítelo tres veces) <br> Durante siete días repite 72 veces al día (sintiendo la Luz del Universo):  Retorno a la Fuente llenándome de la Luz del PADRE Universo me siento con más Energía, más Feliz, Amorosa y Completo. Creo en Mí.  ",
  "<span style='line-height: 1.5;'>Pon atención a tu corazón y desde ahí manifiesta:   <br>“A través de la Luz del Creador elimino toda la energía densa dentro de mí, la distorsión y las memorias no resueltas de mi alineación con todo lo que es esencial en la vida, y el estrés emocional de ser testigo de que todo lo que amo profundamente sufre la total falta del sustento esencial para la vida” .repítelo 3 veces.  <br>Ahora di:  “Activo la verdad del Creador que me refleja su Luz, Amor y Paz. <br>Esta Bendición me da salud, fuerza de vida y el sustento esencial para la vida en la Tierra.”  ",
  "<span style='line-height: 1.5;'>Diles en voz alta:  <br>Quiero disculparme con ustedes por no tenerlos presentes en mi vida. <br>A veces, al sentir su presencia, me asusto y no me siento digno de tenerlos a mi lado. <br>También debo confesar que, en ocasiones, me siento molesto con ustedes por dejarme solo en eventos infelices, y me cuesta entender que es por su infinito Amor que no intervienen, porque son mis aprendizajes de existencia y me ayudan a conocerme a mí mismo, quien realmente SOY YO” (Repite tres veces). <br>Durante siete días antes de levantarte e irte a dormir repite tres veces:  Desde mi corazón les Agradezco por permanecer conmigo a cada momento, a cada instante de mi vida. Me comprometo conmigo mismo a escucharlos y dejarme guiar en su infinito Amor, en cada paso de mi existencia, para mantenerme en mi camino y sé que, aunque me desvíe siempre podre contar con sus directrices para retomarlo, y entender en el sentir, la comprensión del aprendizaje y dejar atrás los lamentos que me atrasan en mi evolución. <br>Les doy Gracias. ASÍ ES (Repite tres veces).  ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>   <br>Soy consciente de que mi Fuerza de voluntad esta entrelazada con la Fuerza de Creador que me permite empoderarme de mi mismo y me protege contra miradas negativas, de envidia y contra las malas intenciones de otros.  <br>Me lleno de la Luz del Creador derramando Compasión a mis sentimientos de venganza, frustración, traición, injusticia y con ello tengo la fuerza para ver con claridad los aprendizajes. <br>Los cuales agradezco desde mi corazón (Repítelo 3 veces)  ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>   <br>“pido a mis Hermanos Mayores, Maestros y Guías apoyo para limpiar y purificar este espacio de cualquier negatividad, residuo, basura, códigos, que no me permitan continuar mi camino de Desarrollo personal y armonizarlo con sentimientos puros de Amor y Compasión (Repítelo tres veces)”  <br>Recomendación:  Limpia el espacio físicamente quemando o en cocimiento de alguna planta para tal fin (ejemplo: romero, eucalipto, laurel, palo santo) y si tu piso es de baldosa límpialo con agua vinagre y siempre con la intención de limpiar y purificar. <br>Al final puedes rociar agua de rosas o pino o la que te llame a ti la atención, agradeciéndole por apoyarte a armonizar el lugar.    ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>   <br>“Manifiesto desde mi corazón el Amor del Creador y lo dejo vibrar llenando mi cuerpo, mi mente, mis emociones. Ahora sé que mi propósito en la vida, es poseer alegría y satisfacción verdadera.  <br>Solamente a través del Amor Incondicional que tengo y dejo reflejar desde mi corazón serán revelados las verdades y los milagros en mi vida” (Repítelo tres veces).  <br>Recomendación: Repítelo durante 21 días 72 veces al día  ",  
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>   <br>“Me rindo a fluir en la corriente divina en cada momento y recibo la paz interior de la Presencia Divina que me permite vivir el cielo en la tierra todos los días”  <br> Cada día enciendo mi Luz para mi propia iluminación y a través de esa luz apoyo a los demás. <br>Vivo en estado de asombro, en estado pleno y feliz (Repítelo tres veces). <br> Recomendación: Repítelo durante 21 días seguidos tres veces antes de levantarte y tres antes de irte a dormir.  ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>   <br>“Activo la verdad como la reconciliación compasiva de que todos somos hermanos y hermanas y remuevo todas las fronteras, credos, religiones, sexos y barreras físicas que separan a los humanos entre sí” (Repite 3 veces) Durante 21 días todas las mañanas repite: <br>Soy consciente de que la paz mundial comienza conmigo. La paz florece cuando ofrezco tolerancia incondicional a mis congéneres. <br>Con completa convicción, sé que mis esfuerzos están cambiando al mundo entero en ese preciso instante. <br>Con la ayuda de mi luz Espiritual, busco en lo profundo de mi Alma y encuentro mi propia Paz, la cual contribuye fundamentalmente a la Paz mundial. ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>   <br>Cuando necesito tomar una decisión importante o recibir respuesta a una pregunta, me conecto a mi luz del corazón y hago un llamado a mi Yo Superior, a mis Maestros y Guías para que me asistan. <br>Confío en que ellos me guiarán hacia la mejor decisión o respuesta para mí en este momento, incluso si parece que no es la correcta. <br>Sé que cualquier respuesta que reciba será una bendición en mi camino y me ayudará a crecer y evolucionar como persona” (Repítelo 3 veces)  <br>Repítelo durante 7 días antes de dormirte tres veces seguidas.  ",  
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>  <br> “Reconozco que me encuentro en un estado de duda y depresión.   <br>Con la ayuda de mi luz, que está en mi corazón, siento el impulso de levantarme, de seguir adelante, de aprender y disfrutar la vida. <br>Mi vida es perfecta, me acepto tal y como soy, porque soy única e irrepetible.  <br>Trabajo día a día para hacer lo mejor para mí, para mis seres queridos y para toda la humanidad.<br> Me esfuerzo por ser la mejor versión de mí mismo, para poder contribuir al bienestar de los demás y del mundo que me rodea. Cada día es una oportunidad para aprender, crecer y mejorar, y estoy comprometido con este proceso de evolución personal y espiritual. Al hacerlo, puedo crear un impacto positivo en mi entorno y en el mundo, y contribuir a la elevación de la conciencia colectiva (Repítelo 3 veces)  <br>Recomendación: repítelo durante 21 días seguidos preferiblemente antes de irte a dormir.  <br>Adicionalmente cuando te levantes de la cama, sonríe, levanta la mirada, enderézate (pon la espalda derecha) y levanta tus brazos en señal de victoria. Grita de júbilo, ríete, siente a tu corazón saltar de alegría.   <br>Utiliza esta “postura física de grandeza” todas las veces que la requieras.   <br>Siempre que te veas al espejo sonríe sin importar que sea al principio una mueca. Al sonreír le indicas al subconsciente que si se puede ser feliz.  ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>  <br> “Estoy rompiendo las barreras que me mantienen encerrado y estoy abriendo mi mente y mi corazón a nuevas posibilidades. <br>Estoy dispuesto a explorar el mundo que me rodea y a descubrir todo lo que la vida tiene para ofrecer.<br> Me libero de mis miedos y limitaciones y me permito ser libre y feliz. <br>Estoy en el flujo de mi vida y tomo decisiones conscientes y sabias que me llevan hacia un futuro brillante y lleno de posibilidades. <br>Soy capaz de superar cualquier obstáculo y alcanzar mis metas y sueños” (Repítelo 3 veces). <br> Recomendación. Antes de levantarte de la cama y cada vez que te veas al espejo sonríe (sin importar que sea al principio una mueca) y siente tu fuerza que emerge desde la parte baja del abdomen y de tu corazón.   ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>  <br> Respiro y en cada respiración soy consciente de que estoy conectado al Creador. <br>Siento su presencia en mi interior y en todo lo que me rodea.<br> Desde el latido de mi corazón, recuerdo que yo soy el Creador de mi existencia y que tengo el poder de crear una vida llena de prosperidad y abundancia. <br>Comparto esta riqueza con todos aquellos que están desarrollando nuevas ideas y prácticas, y juntos creamos un mundo mejor para todos (Repítelo 3 veces).  ",  
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>  <br>Anclo en mí el amor, la sabiduría y el poder del Creador, que me permite crear una vida llena de significado y propósito. Puedo manifestar mis deseos y sueños en la realidad física y contribuir al bienestar de los demás y del mundo que me rodea. Soy un ser poderoso y creativo, capaz de crear un futuro brillante y lleno de posibilidades para mí y para todos aquellos que me rodean. <br>Al conectarme con el Creador, puedo alcanzar mi máximo potencial y vivir una vida plena y satisfactoria (Repítelo 3 veces). <br> Recomendación: repítelo durante nueve días seguidos tres veces al día.  ",
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>  <br>Me hago consciente y responsable de los malos hábitos que poseo y he venido contemplando. <br>La Luz del Creador me asiste en esta transformación y me provee de la fuerza suficiente para soltar mi adicción. <br>Así mismo, me ofrece la aventura de vivir disfrutando la vida y de sus maravillas cada día, las cuales yo recibo en amor y gratitud (repítelo tres veces).  <br>Recomendación: repite durante 21 días seguidos tres veces al día.  ",
  // 21
  "<span style='line-height: 1.5;'><em>Di en voz alta:</em>  <br>Me libero de la distorsión y las memorias no resueltas del miedo y el dolor de estar abandonado y separada del amor de Creador. <br>Acepto su Amor y siento como vibra en mi corazón – Esencia sanando cualquier sentimiento de abandono con su gran Abrazo que me llena cualquier vacío que pueda tener. <br>Me siento pleno y completo al recibir su amor incondicional (repítelo tres veces)    <br>Recomendación: repítelo por siete días seguidos"
  // This is carta Afirmacion
];


function gotoNewPage(selNumber) {
  
  var randomNumberIndex = selNumber;
  // var randomNumberIndex = Math.floor(Math.random() * cartaNumbers.length);
  // Generate a random number between 1 and 40
  var ranSelNum = Math.floor(Math.random() * 21) + 1;

  // var randomNumber = randomNumberIndex + 1
  var randomNumber = ranSelNum
  var cartaNumber = cartaNumbers[randomNumber];
  var pageTitle = pageTitles[randomNumber];
  var pageContent = pageContents[randomNumber];
  var pageMed = contentMeds[randomNumber];
  var contentAfir = contentAfirs[randomNumber];


      // Save the randomly selected content in sessionStorage
      sessionStorage.setItem("randomNumber", randomNumber);
      sessionStorage.setItem("cartaNumber", cartaNumber);
      sessionStorage.setItem("pageTitle", pageTitle);
      sessionStorage.setItem("pageContent", pageContent);
      sessionStorage.setItem("pageMed", pageMed);
      sessionStorage.setItem("contentAfir", contentAfir);


      // loadPageCartas(function(cartaTitle_json) {
      //   // Use the retrieved pageTitles array in your code
      //   sessionStorage.setItem("cartaTitle_json", cartaTitle_json);

      //   console.log(cartaTitle_json);
      // }
      // );
      // Im using json.fecth to retrieve data from my json file

// new code
    // var data = JSON.parse(data.json);
    //       fetch('data.json')
    //       .then(response => response.json())
    //       .then(data => {
    //         var title = "";
    //         for (var i = 0; i < data.length; i++) {
    //           if (data[i].id === 2) {
    //             title = data[i].title;
    //             sessionStorage.setItem("cartaTitle_json", title);
    //             break;
    //           }
    //         }
    //   console.log(title); // Output: 2 Causa y Efecto 2
    // })
    // .catch(error => {
    //   console.log('Error:', error);
    // });
  
// up to here


  // Open the random-page.html in a new window and pass the title and content as query parameters
  var url = "cartas.html" + "?cartaNumber=" + encodeURIComponent(cartaNumber) + "&randomNumber=" + encodeURIComponent(randomNumber)  + "&pageTitle=" + encodeURIComponent(pageTitle)+ "&pageContent=" + encodeURIComponent(pageContent)+ "&pageMed="  + encodeURIComponent(pageMed)+ "&contentAfir="  + encodeURIComponent(contentAfir);
  // window.open(url, "_blank");
  window.open("cartas.html", "_blank");
}

function handleKeyPress(event) {
  if (event.key === "Enter") {
    var selNumber = event.target.value;
    console.log("Selected number:", selNumber);
    // Call your function or perform actions with the selected number
    gotoNewPage(selNumber-1);
  }
}

function greetUser(name) {
  console.log("Hello, " + name + "!"); // Replace with your desired code
}

function handleClick() {
  var inputElement = document.getElementById("nameInput");
  var selNumber = inputElement.value;
  console.log("Selected number:", selNumber);
  // Call your function or perform actions with the selected number
  greetUser(selNumber);
}

var button = document.getElementById("submitButton");
button.addEventListener("click", handleClick);


// up to here

// Attach the event listener to the document or specific element
document.addEventListener("keydown", handleKeyPress);


// function loadPageCartas(callback) {
//   var xhr = new XMLHttpRequest();
//   xhr.overrideMimeType("application/json");
//   xhr.open("GET", "data.json", true);
//   xhr.onreadystatechange = function() {
//     if (xhr.readyState === 4 && xhr.status === 200) {
//       var response = JSON.parse(xhr.responseText);
//       callback(response.title);
//     }
//   };
//   xhr.send(null);
// }
